swagger: "2.0"
info:
  title: Channel Service API
  description: Micro-service de gestion des canaux IRC (création, configuration, ACLs)
  version: 1.0.0

servers:
  - url: http://localhost:5001

paths:
  /channel:
    get:
      summary: Lister les canaux publics
      responses:
        '200':
          description: Liste des canaux publics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Channel'
    post:
      summary: Créer un nouveau canal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, private]
              properties:
                name:
                  type: string
                private:
                  type: boolean
      responses:
        '201':
          description: Canal créé avec succès
        '409':
          description: Canal déjà existant

  /channel/{name}/users:
    get:
      summary: Lister les utilisateurs d’un canal
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Liste des utilisateurs du canal
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /channel/{name}:
    patch:
      summary: Modifier le sujet et/ou les modes d’un canal
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                topic:
                  type: string
                mode:
                  type: string
      responses:
        '200':
          description: Modification appliquée
        '403':
          description: Non autorisé

    delete:
      summary: Supprimer un canal
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Canal supprimé
        '403':
          description: Non autorisé

  /channel/{name}/topic:
    post:
      summary: Modifier uniquement le sujet
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [topic]
              properties:
                topic:
                  type: string
      responses:
        '200':
          description: Sujet mis à jour
        '403':
          description: Non autorisé

  /channel/{name}/mode:
    post:
      summary: Ajouter un mode à un canal
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [mode]
              properties:
                mode:
                  type: string
                  example: "+r"
      responses:
        '201':
          description: Mode ajouté
        '409':
          description: Mode déjà présent

  /channel/{name}/config:
    get:
      summary: Récupérer la configuration complète d’un canal
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Configuration du canal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'

  /channel/{name}/invite:
    post:
      summary: Inviter un utilisateur dans un canal
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [pseudo]
              properties:
                pseudo:
                  type: string
      responses:
        '200':
          description: Utilisateur invité
        '403':
          description: Non autorisé

  /channel/{name}/ban:
    post:
      summary: Bannir un utilisateur d’un canal
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [pseudo, reason]
              properties:
                pseudo:
                  type: string
                reason:
                  type: string
      responses:
        '200':
          description: Utilisateur banni
        '403':
          description: Non autorisé

components:
  schemas:
    Channel:
      type: object
      properties:
        name:
          type: string
        private:
          type: boolean
        topic:
          type: string
        owner:
          type: string
        moderators:
          type: array
          items:
            type: integer
        invited:
          type: array
          items:
            type: integer
        banned:
          type: array
          items:
            type: integer
        modes:
          type: array
          items:
            type: integer
        created_at:
          type: string
          format: date-time
